### ISSUE TITLE
Support modified key clicks (or TabSubmit Basic) to open in a new tab

### ISSUE THREAD

**Issue by grahamperrin** [milzer/firefox-link-filter#2]
Please, can you make the list of links support <kbd>Control</kbd>-Click or (on Mac OS X) <kbd>Command</kbd>-Click?

I have [TabSubmit Basic](https://addons.mozilla.org/addon/tabsubmit-basic/) enabled but it seems to be ineffective with the list. 

Thanks

**Comment by milzer** [comment]
I totally missed this whole issue as I didn't receive e-mail notification about it. Sorry about the huge delay. The support for control/cmd-click has now been added and updated to addons.mozilla.org
